name: Machine Learning Pipeline CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  eksekusi-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Kode dari Repositori
        uses: actions/checkout@v3

      - name: Pasang Sistem Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Pasang Seluruh Dependensi Pustaka
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn pandas matplotlib

      - name: Eksekusi Otomatis MLflow Project (Bypass Conda)
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          cd MLProject
          mlflow run . --env-manager local --entry-point tuning
